cask_args appdir: "/Applications"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

# Dev
brew "hivemind"
brew "kubectl"
cask "google-cloud-sdk"
brew "sqlite"
brew "ansible"
brew "postgresql", restart_service: true
brew "redis", restart_service: true

# Tools
cask "google-chrome"
cask "appcleaner"
cask "the-unarchiver"
cask "tunnelbear"
cask "transmission"
cask "zoomus"
cask "sublime-text"
cask "sublime-merge"
cask "visual-studio-code"
cask "docker"

# Mac App Store items
brew "mas"
mas "Telegram", id: 747648890
mas "Flow", id: 1423210932
